---
language: python
python: "3.9"

# Use the new container infrastructure
sudo: required

before_install:
 - sudo useradd -d /home/ansible-test-user ansible-test-user
 - sudo mkdir /home/ansible-test-user
 - sudo chown ansible-test-user:ansible-test-user /home/ansible-test-user

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install -r requirements.txt
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
