---
- name: Download ASC file
  get_url:
    url: "{{ vscode_microsoft_asc_url }}"
    dest: /tmp/microsoft.asc

- name: Update software cache for apt-get
  become: True
  apt:
    update_cache: yes
  changed_when: False

- name: Install GNU Privacy Guard
  apt:
    name: gpg
    state: present

- name: Convert ASC file for GPG file
  command: "gpg --dearmor /tmp/microsoft.asc > /etc/apt/trusted.gpg.d/microsoft.gpg"
  changed_when: False

- name: Update software cache for apt-get yet again
  become: True
  apt:
    update_cache: yes
  changed_when: False

- name: Install Visual Studio Code
  apt:
    name: code
    state: present
