---
- name: Update software cache for apt-get
  become: True
  apt:
    update_cache: yes
  changed_when: False

- name: Install GPG
  apt:
    name: gpg
    state: present

- name: Download ASC file
  apt_key:
    url: "{{ vscode_microsoft_asc_url }}"
    state: present

- name: Copy repo list
  ansible.builtin.copy:
    src: vscode.list
    dest: /etc/apt/sources.list.d/vscode.list
    mode: '0644'

- name: Update software cache for apt-get again
  become: True
  apt:
    update_cache: yes
  changed_when: False

- name: Install Visual Studio Code
  apt:
    name: code
    state: present
