---
- name: Install required software
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ vscode_fedora_required_software | flatten }}"

- name: Import RPM key
  ansible.builtin.rpm_key:
    key: "{{ vscode_microsoft_asc_url }}"
    state: present

- name: Create rpm repository file
  ansible.builtin.copy:
    src: vscode.repo
    dest: /etc/yum.repos.d/vscode.repo
    mode: '0644'

- name: Install Visual Studio Code
  ansible.builtin.package:
    name: code
    state: present
