---
- name: Import RPM key
  rpm_key:
    key: "{{ vscode_microsoft_asc_url }}"
    state: present

- name: Create rpm repository file
  template:
    src: vscode.repo.j2
    dest: /etc/yum.repos.d/vscode.repo

- name: Install Vistual Studio Code
  package:
    name: code
    state: present
