---
- name: Import RPM key
  rpm_key:
    key: "{{ vscode_microsoft_asc_url }}"
    state: present

- name: Create rpm repository file
  ansible.builtin.copy:
    src: vscode.repo
    dest: /etc/yum.repos.d/vscode.repo
    mode: '0644'

- name: Install Vistual Studio Code
  package:
    name: code
    state: present
