---
- name: Converge
  hosts: all
  vars:
    config_owner: ansible-test-user
    vscode_extensions:
      - 'HookyQR.beautify'
  tasks:
    - name: "Include ansible-role-vscode"
      ansible.builtin.include_role:
        name: "ansible-role-vscode"
